name: Build Flutter App

on:
  push:
    branches: [ main ] # Adjust if your main branch is named differently
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Or specify a specific version
          channel: 'stable' # Or 'beta', 'dev'

      - run: flutter pub get

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          flutter build linux

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: |
          flutter build windows

      - name: Upload Artifacts (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/
